### ISSUE TITLE
Desktop Duplication Custom Output

### ISSUE THREAD

**Issue by AhmedX6** [arBmind/desktop-duplication-cpp#1]
Hello arBmind,
I try to recreate the project that you did, with the only difference, that I want to send the buffer on the network.
I would like to know if it was possible to customize the output of the frame. For example, I have my desktop which is in 1920x1080, I would like to be able to receive the buffer and dirty rect in 1280x720.
I saw that there was the SetDisplaySurface function that could be applied before running DuplicateOutput.
Here is my code:
```
HRESULT hr;

 hr = gDevice->QueryInterface(IID_PPV_ARGS(&gDxgiDevice));
		if (FAILED(hr))
			return;
		hr = gDxgiDevice->GetParent(__uuidof(IDXGIAdapter), reinterpret_cast<void**>(&gDxgiAdapter));
		if (FAILED(hr))
			return;
		gDxgiDevice->Release();
		UINT Output = 0;
		IDXGIOutput *lDxgiOutput = nullptr;
		hr = gDxgiAdapter->EnumOutputs(Output, &lDxgiOutput);
		if (FAILED(hr))
			return;
		gDxgiAdapter->Release();
		hr = lDxgiOutput->GetDesc(&gOutputDesc);
		if (FAILED(hr))
			return;
		IDXGIOutput1 *lDxgiOutput1 = nullptr;
		hr = lDxgiOutput->QueryInterface(IID_PPV_ARGS(&lDxgiOutput1));
		if (FAILED(hr))
			return;
		lDxgiOutput->Release();
//Is it possible to customize the output here ? With SetDisplaySurface ?
		hr = lDxgiOutput1->DuplicateOutput(gDevice, &gDeskDupl);
		if (FAILED(hr))
			return;
		lDxgiOutput1->Release();
		gDeskDupl->GetDesc(&gOutputDuplDesc);
```
Is it possible for you to help me?
Thanks a lot

**Comment by arBmind** [comment]
Sorry, this is explicitly not a goal of this project. What you want is more like VNC. You should take a look there.
