### ISSUE TITLE
Capture the desired window

### ISSUE THREAD

**Issue by xeeetu** [arBmind/desktop-duplication-cpp#10]
Hello, I really like your work, you have done a great job. I have a question, is it possible to take a screenshot not of the whole desktop but just one application? Take a screenshot of the desktop and cut out the layers with unnecessary applications? I will be grateful for any answer.

**Comment by arBmind** [comment]
Hi @xeeetu, thanks for the praise.

The aim of this program is to share a portion of the screen.

I assume that Windows can capture a specific window.
What I don't know if this would work on the graphics card level.
Also the problem with this is that, secondary windows like dialogs would not be captured.
So far I preferred to capture the region of the screen where a window is placed.

On the other hand it may be possible to cut out windows you don't want to be captured.
But tracking all the windows on the desktop seems also bit too much work.

Can you describe your use case a bit more?

**Comment by xeeetu** [comment]
@arBmind Right now I am cutting out an area on the screen. In this area there are some transparent windows with information that are in my way. I want to take a screenshot of the area and exclude these windows from it. What methods can I use to do this?

**Comment by arBmind** [comment]
@xeeetu I don't think that is easily possible, as on GPU level everything is composed into one framebuffer.
