### ISSUE TITLE
Black output

### ISSUE THREAD

**Issue by akshit-sharma** [arBmind/desktop-duplication-cpp#4]
I compiled this repository in Visual Studio Professional 2017.

The only difference being, I switched all paths in desktop-duplication.vcxproj from Community to Professional. 
It compiles just fine. Running the program gives me the following black display.

![image](https://user-images.githubusercontent.com/2051760/48992745-c4d95a80-f0f6-11e8-9e31-564331ccb110.png)

Do you have an idea what can be causing this issue ?

**Comment by arBmind** [comment]
Your icon is red, this means the initialization of the mirroring source failed somehow with an exception.
You should see some hints in the "Output" tab of Visual Studio 2017.

**Comment by akshit-sharma** [comment]
It says ``` Failed to get duplication output from device ```

Failed duplication output should be triggered from capture_thread.cpp:136, but I don't know, how to fix this.

**Comment by akshit-sharma** [comment]
It is working on my secondary display but not the primary one. But I will close the issue.
