### ISSUE TITLE
Setup Visual Studio Project

### ISSUE THREAD

**Issue by ml-jo** [arBmind/desktop-duplication-cpp#9]
Hi @arBmind, 

thanks a lot for this great tool. I am using it for sharing just a part of my screen in MS-Teams Meetings. To further customize the tool to my needs, I want to add a few changes.  Unfortunately, I am not able to set up the Project in Visual Studio 2019 (Professional). 

I have already installed the Windows 10 SDK and used the clang Toolset, but I receive the following Error-message: 

'''
..\..\src\BaseRenderer.cpp(5,10): fatal error : 'PlainPixelShader.h' file not found
'''

Therefore, I suspect something is still wrong with my include directories.  Since I am not very experienced with Direct-X development, I appreciate any tips. Thanks a lot for your help.

**Comment by arBmind** [comment]
Hi @ml-jo,

I'm pleased to hear that you use and like my little tool here.

I would guess the clang Toolset is advisable needed here. I suggest to stick with the default compiler.
This project was never meant to be compiled with Visual Studio directly. Qbs is a far superior build system.

From inspecting my rusty knowledge:
* 'PlainPixelShader.h' is generated from the 'PixelShader.hlsl'. Ensure you added these shaders to your project and can compile them.
  * You also need to mark the shaders as Pixelshader and Vertexshader respectively.
  * They use the shader model `4_0_level_9_3`
* `<AdditionalIncludeDirectories>$(OutDir)</AdditionalIncludeDirectories>` - so the compiler finds the generated headers.
* Define `NOMINMAX` on the build system
* Add `d3d11` as link library.

I hope you can make it work for you and hope to see some cool pull requests with shiny features.

**Comment by arBmind** [comment]
This repo had a .vcproj until this commit: https://github.com/arBmind/desktop-duplication-cpp/tree/e49ecefc9b9f5a4736a645c41e49ccdfb6b015fb
It became painful to maintain two build systems so I removed it for the next refactoring.
But it might contain the details you need to get it working for you.

**Comment by ml-jo** [comment]
Thank you for the quick responses and the advice. The old commit helped me a lot to set up the project. 
I will definitely propose my changes as a pull request. I am glad to participate in this great project.
